# Generated by Django 5.0 on 2023-12-14 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfs',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='blah',
        ),
        migrations.AddField(
            model_name='pdfs',
            name='file_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfs',
            name='publication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfs',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfs',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfs',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
