# Generated by Django 5.0 on 2023-12-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_pdfs_file_name_remove_userprofile_blah_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserProfiles',
        ),
    ]
