# Generated by Django 5.0 on 2023-12-15 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_userprofiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfs',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.userprofiles'),
        ),
    ]
