# Generated by Django 5.0 on 2023-12-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_profile_pdfs_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfs',
            name='user_profile',
        ),
    ]
