# Generated by Django 5.0 on 2023-12-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_pdfs_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfs',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='pdfs',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='pdfs',
            name='url',
        ),
        migrations.RemoveField(
            model_name='pdfs',
            name='year',
        ),
    ]
