# Generated by Django 5.0 on 2023-12-18 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_pdfs_file_path_remove_pdfs_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfs',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
