# Generated by Django 5.0 on 2023-12-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_pdfs_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfs',
            name='file_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
